name: "Second yml"

on: 
  push:
    branches:
      - main

jobs:
  job1:
    name: this is first job
    runs-on: ubuntu-latest
    steps: 
    - name: Step one
      uses: actions/checkout@v2
    - name: step two
      run: env | sort
  job2:
    name: this is second job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: step two
      run: "Get-ChildItem Env: | Sort-Object Name"
